controller_manager:
  ros__parameters:
    update_rate: 500
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    mg400_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

mg400_arm_controller:
  ros__parameters:
    joints:
      - mg400_j1
      - mg400_j2_1
      - mg400_j3_1
      - mg400_j4_1
      - mg400_j5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false